const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='jgsSkillLinksV11';
let KB=null,enginePromise=null,ready=false,current=null;
let skillById,skillByName,entityById,aliasMap,termMap,pairMap,outMap,abilityById,mechanismById,negativeMap,allSkills=[];
const clamp=x=>Math.max(0,Math.min(1,x));
const norm=x=>String(x||'').trim().toLowerCase().replace(/[’]/g,"'").replace(/\s+/g,' ');
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]));
const curated={
  'skiing|association football':{unit:'SINGLE-LEG DYNAMIC BALANCE',def:'Control your centre of mass over one support leg while the other leg moves and direction changes.',why:'Skiing repeatedly loads one leg and manages centre of mass through turns, speed changes and terrain. Football asks for the same body-control problem when kicking, passing, dribbling, cutting, shielding and recovering after contact.',help:'You may have a head start staying stable while one leg supports your body and the free leg acts on the ball or changes direction.',transfer:'LOAD ONE LEG → CONTROL CENTRE OF MASS → MOVE THE FREE LEG → RECENTRE → CHANGE DIRECTION',use:'Kicking · passing · dribbling · cutting · shielding · contact recovery',new:'Ball control, passing technique, shooting, scanning, tactical positioning and football-specific decisions still require direct practice.',test:'Try slow single-leg ball touches, passes and cuts. Compare control when you deliberately use the same centred, loaded-leg feeling you use when skiing.'},
  'magic|association football':{unit:'INTENTION CONCEALMENT + FALSE-CUE GENERATION',def:'Make another person predict the wrong action by controlling visible cues while protecting your real intention.',why:"Magic deliberately manipulates an observer's expectations. Football feints, disguised passes and body swerves use the same prediction-control problem.",help:'You may understand deception earlier than a beginner who only thinks about the physical movement.',transfer:'SHOW A BELIEVABLE CUE → LET THE DEFENDER COMMIT → EXECUTE THE REAL ACTION',use:'Body feints · fake shots · disguised passes · changes of direction',new:'Football timing, ball control, pace, defender distance and tactical context remain specific to football.',test:'Practise one feint slowly. Judge success by whether the defender reacts to the false cue, not by how dramatic the movement looks.'},
  'knitting|programming':{unit:'STATE TRACKING + ERROR TRACING',def:'Maintain where you are in a structured sequence and trace a mismatch back to the point where state changed incorrectly.',why:'Knitting requires tracking stitch state, pattern position and mistakes across a sequence. Programming requires tracking program state, execution order and the source of errors.',help:'You may already be comfortable with structured sequences, local errors and correcting a process without restarting everything.',transfer:'TRACK STATE → NOTICE MISMATCH → TRACE BACK → CORRECT THE LOCAL STEP → CONTINUE',use:'Debugging · loops · sequence logic · stateful programs',new:'Syntax, data structures, algorithms and software architecture remain programming-specific.',test:'When debugging a tiny program, write down the expected state after each step as you would count pattern progress in knitting.'},
  'drum kit|language learning':{unit:'RHYTHMIC TIMING + SOUND-SEQUENCE CHUNKING',def:'Track repeating sound patterns, timing accents and sequence structure as one organised unit.',why:'Drumming trains timing, subdivision and recurring sound sequences. Spoken language also contains stress, rhythm, timing and repeatable sound chunks.',help:'You may pick up speech rhythm and pronunciation patterns faster than someone treating every syllable separately.',transfer:'HEAR THE PHRASE AS RHYTHM → MARK STRESS → COPY THE TIMING → ADD WORDS',use:'Pronunciation · sentence stress · listening · shadowing',new:'Vocabulary, grammar, meaning and language-specific sounds still require direct learning.',test:'Shadow one short sentence as if it were a drum phrase before focusing on the exact words.'}
};
curated['skiing|football']=curated['skiing|association football'];
curated['magic|football']=curated['magic|association football'];
curated['drumming|language learning']=curated['drum kit|language learning'];
function setEngine(text,kind=''){let el=$('#engineStatus');if(!el){el=document.createElement('div');el.id='engineStatus';el.className='engine-status';$('.examples')?.after(el)}el.className='engine-status '+kind;el.textContent=text}
function bytesFromBase64(b64){const bin=atob(b64),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function gunzipText(b64){if(!('DecompressionStream' in window))throw new Error('Your browser needs current gzip-stream support. Please update Chrome, Edge, Firefox or Safari.');const stream=new Blob([bytesFromBase64(b64)]).stream().pipeThrough(new DecompressionStream('gzip'));return new Response(stream).text()}
async function ensureEngine(){if(ready)return KB;if(enginePromise)return enginePromise;setEngine('Loading the full Skill Universe…','loading');enginePromise=(async()=>{const manifest=await fetch('runtime-manifest.json',{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('Runtime manifest could not be loaded.');return r.json()});const parts=await Promise.all(manifest.parts.map(p=>fetch(p,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(`Runtime part failed: ${p}`);return r.text()})));const raw=await gunzipText(parts.join('').replace(/\s+/g,''));KB=JSON.parse(raw);buildIndexes();ready=true;const explicit=Number(KB.meta?.runtime?.validated_explicit_connections_loaded||KB.connections?.length||0);setEngine(`${allSkills.length.toLocaleString()} skills ready · ${explicit.toLocaleString()} explicit mapped Skill-Links · local runtime`,'ready');populateDatalist();return KB})().catch(err=>{setEngine(err.message||'Could not load the Skill Universe.','error');throw err});return enginePromise}
function buildIndexes(){skillById=new Map();skillByName=new Map();entityById=new Map();aliasMap=new Map();termMap=KB.terms||{};pairMap=new Map();outMap=new Map();abilityById=new Map(Object.entries(KB.abilities||{}));mechanismById=new Map(Object.entries(KB.mechanisms||{}));negativeMap=new Map((KB.negative||[]).map(x=>[x[0]+'|'+x[1],x]));for(const s of KB.skills||[]){const o={id:s[0],name:s[1],aliases:s[2]||[],domains:s[3]||[],dims:s[4]||[],abilities:s[5]||[],mechanisms:s[6]||[],description:s[7]||'',subskills:s[8]||[],micros:s[9]||[],type:'skill'};skillById.set(o.id,o);skillByName.set(norm(o.name),o);entityById.set(o.id,o);for(const a of o.aliases)if(!aliasMap.has(norm(a)))aliasMap.set(norm(a),o)}for(const e of KB.entities||[]){const o={id:e[0],name:e[1],type:e[2],aliases:e[3]||[],skillIds:e[4]||[],abilities:e[5]||[],description:e[6]||''};entityById.set(o.id,o);for(const a of [o.name,...o.aliases])if(!aliasMap.has(norm(a)))aliasMap.set(norm(a),o)}for(const c of KB.connections||[]){const k=c[1]+'|'+c[2];if(!pairMap.has(k))pairMap.set(k,[]);pairMap.get(k).push(c);if(!outMap.has(c[1]))outMap.set(c[1],[]);outMap.get(c[1]).push(c)}pairMap.forEach(v=>v.sort((a,b)=>b[3]-a[3]));outMap.forEach(v=>v.sort((a,b)=>b[3]-a[3]));const manualAliases={'football':'Association football','coding':'Programming','code':'Programming','drumming':'Drum kit','drums':'Drum kit','soccer':'Association football','3d modeling':'3D modelling','cross fit':'CrossFit'};for(const [a,nm] of Object.entries(manualAliases)){const x=skillByName.get(norm(nm));if(x)aliasMap.set(a,x)}allSkills=[...skillById.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function populateDatalist(){const dl=$('#skillList');if(!dl||dl.dataset.ready)return;const frag=document.createDocumentFragment();for(const s of allSkills){const o=document.createElement('option');o.value=s.name;frag.append(o)}dl.replaceChildren(frag);dl.dataset.ready='1'}
function candidateEntity(c){return entityById.get(c?.id||c?.[0])}
function resolve(text){const n=norm(text);if(!n)return null;let e=skillByName.get(n)||aliasMap.get(n);if(e)return e;const cs=(termMap[n]||[]).slice().sort((a,b)=>(b.weight||0)-(a.weight||0));for(const c of cs){e=candidateEntity(c);if(e)return e}const tokens=n.split(/[^a-z0-9+#.]+/).filter(Boolean);let best=null,bestScore=0;for(const s of allSkills){const sn=norm(s.name),st=sn.split(/[^a-z0-9+#.]+/).filter(Boolean);let inter=0;for(const t of tokens)if(st.includes(t))inter++;const score=inter/Math.max(tokens.length,st.length)+((sn.includes(n)||n.includes(sn))?.25:0);if(score>bestScore){bestScore=score;best=s}}return bestScore>=.45?best:null}
function entitySkillIds(ent){if(!ent)return[];return ent.type==='skill'?[ent.id]:(ent.skillIds||[]).filter(id=>skillById.has(id))}
function mechanismName(id){return mechanismById.get(id)?.[0]||String(id||'shared process').replace(/^mechanism_/,'').replaceAll('_',' ')}
function mechanismSpec(id){return mechanismById.get(id)?.[3]??.5}
function abilityName(id){return abilityById.get(id)?.[0]||String(id||'').replace(/^ability_/,'').replaceAll('_',' ')}
const tooGeneric=/^(focus|discipline|patience|persistence|teamwork|communication|problem solving|coordination|attention)$/i;
function bestUnit(path){const mids=[...(path.mechanisms||[])].sort((a,b)=>mechanismSpec(b)-mechanismSpec(a));for(const id of mids){const n=mechanismName(id);if(!tooGeneric.test(n)&&mechanismSpec(id)>=.30)return n}for(const id of path.abilities||[]){const n=abilityName(id);if(!tooGeneric.test(n))return n}return mids.length?mechanismName(mids[0]):'specific shared process'}
function mappedPath(c,sourceId,targetId){const neg=negativeMap.has(sourceId+'|'+targetId)?Math.max(c[17]||0,.35):(c[17]||0);const spec=Math.max(...(c[5]||[]).map(mechanismSpec),c[16]||0);const score=clamp((c[3]||0)-.14*neg+.08*spec);if(score<.27||neg>.8)return null;return{kind:'mapped',sourceId,targetId,score,mechanisms:c[5]||[],abilities:c[6]||[],evidence:c[8]||'MECHANISM_BASED_INFERENCE',confidence:c[9]||.5,sourceComponent:c[10]||'a repeated source behaviour',destComponent:c[11]||'a target behaviour using the same process',specificity:spec,negative:neg,c}}
function inferredPath(sourceId,targetId){const s=skillById.get(sourceId),t=skillById.get(targetId);if(!s||!t)return null;const tm=new Set(t.mechanisms),ta=new Set(t.abilities);const sharedM=s.mechanisms.filter(x=>tm.has(x)).sort((a,b)=>mechanismSpec(b)-mechanismSpec(a));const sharedA=s.abilities.filter(x=>ta.has(x));if(!sharedM.length)return null;const spec=sharedM.slice(0,4).reduce((n,id)=>n+mechanismSpec(id),0)/Math.min(4,sharedM.length);const overlap=sharedM.length/Math.max(6,Math.min(s.mechanisms.length,t.mechanisms.length));const score=clamp(.18+.36*Math.min(1,overlap*3)+.24*spec+.08*Math.min(1,sharedA.length/4));if(score<.34||spec<.25)return null;return{kind:'inferred',sourceId,targetId,score,mechanisms:sharedM.slice(0,4),abilities:sharedA.slice(0,5),evidence:'MECHANISM_BASED_INFERENCE',confidence:clamp(.32+.38*spec),sourceComponent:'a source behaviour that repeatedly uses this process',destComponent:'a target behaviour that requires the same process',specificity:spec,negative:0}}
function findPath(source,target){let best=null;const sids=entitySkillIds(source).slice(0,24),tids=entitySkillIds(target).slice(0,24);for(const sid of sids)for(const tid of tids){for(const c of (pairMap.get(sid+'|'+tid)||[]).slice(0,3)){const p=mappedPath(c,sid,tid);if(p&&(!best||p.score>best.score))best=p}if(!pairMap.has(sid+'|'+tid)){const p=inferredPath(sid,tid);if(p&&(!best||p.score>best.score))best=p}}if(best)return best;for(const sid of sids.slice(0,8))for(const c1 of (outMap.get(sid)||[]).slice(0,80)){const mid=c1[2];for(const tid of tids.slice(0,8)){const c2=(pairMap.get(mid+'|'+tid)||[])[0];if(!c2)continue;const score=Math.sqrt((c1[3]||0)*(c2[3]||0))*.83;const spec=(mechanismSpec(c1[5]?.[0])+mechanismSpec(c2[5]?.[0]))/2;if(score>=.34&&spec>=.28&&(!best||score>best.score))best={kind:'bridge',sourceId:sid,targetId:tid,bridgeSkillId:mid,score,mechanisms:[...(c1[5]||[]),...(c2[5]||[])].slice(0,4),abilities:[...(c1[6]||[]),...(c2[6]||[])].slice(0,5),evidence:'MECHANISM_BASED_INFERENCE',confidence:Math.min(c1[9]||.5,c2[9]||.5)*.9,sourceComponent:c1[10]||'source behaviour',destComponent:c2[11]||'target behaviour',specificity:spec,negative:Math.max(c1[17]||0,c2[17]||0)}}}return best}
function curatedFor(source,target){return curated[`${norm(source?.name)}|${norm(target?.name)}`]||curated[`${norm($('#source').value)}|${norm($('#target').value)}`]}
function buildResult(source,target,path){const cp=curatedFor(source,target);if(cp)return cp;const unit=bestUnit(path),u=unit.toLowerCase(),bridge=path.kind==='bridge'?skillById.get(path.bridgeSkillId):null;const why=bridge?`${source.name} connects to ${target.name} through ${bridge?.name||'an intermediate skill'}. The strongest shared process is ${u}: the source route uses it in ${path.sourceComponent}, and the target route uses it in ${path.destComponent}.`:`${source.name} repeatedly uses ${u} in ${path.sourceComponent}. ${target.name} requires the same process in ${path.destComponent}. That is the specific overlap JGS is prioritising.`;return{unit:unit.toUpperCase(),def:`Reuse ${u} from ${source.name} inside a concrete ${target.name} task rather than relearning that underlying process from zero.`,why,help:`Your head start is familiarity with ${u}. That can reduce the amount of new control, judgement or sequencing you need to build before focusing on ${target.name}-specific technique.`,transfer:`RECOGNISE THE ${u.toUpperCase()} CUE → APPLY YOUR SOURCE ROUTINE → ADAPT IT TO ${target.name.toUpperCase()} → CHECK THE RESULT`,use:`Look for moments in ${target.name} where ${u} directly changes the quality of the action or decision.`,new:`Technique, rules, tools, timing and context that are unique to ${target.name} still need direct practice.`,test:`Choose one beginner ${target.name} task. Do it once normally, then repeat while deliberately applying ${u}. Compare errors, control and consistency.`,bridge:bridge?.name||null}}
function evidencePlain(path){if(path.kind==='mapped')return 'This route comes from an explicit mapped connection in the materialised JGS runtime. The explanation is still a mechanism-level transfer claim, not a guaranteed outcome.';if(path.kind==='bridge')return 'This is a two-step mechanism-based bridge through another mapped skill. Treat it as a useful route to test, not proof of causal transfer.';return 'This is a mechanism-overlap inference. The shared process is specific enough to test, but the exact pair is not represented as a direct mapped connection.'}
function renderResult(source,target,path){const r=buildResult(source,target,path);current={source:source.name,target:target.name,path,r};$('#result').innerHTML=`<article class="result-card"><div class="result-head"><small>THE EXACT SKILL-LINK</small><h2>${esc(r.unit)}</h2><p>${esc(r.def)}</p></div><div class="answer-grid"><div class="answer"><b>WHY THIS WAS CHOSEN</b><p>${esc(r.why)}</p></div><div class="answer"><b>HOW IT HELPS</b><p>${esc(r.help)}</p></div><div class="answer"><b>HOW TO TRANSFER IT</b><p class="transfer-rule">${esc(r.transfer)}</p></div><div class="answer"><b>USE IT HERE</b><p>${esc(r.use)}</p></div><div class="answer"><b>WHAT IS STILL NEW</b><p>${esc(r.new)}</p></div><div class="answer"><b>TRY THIS NOW</b><p>${esc(r.test)}</p></div></div><div class="evidence-note"><b>Evidence scope:</b> ${esc(evidencePlain(path))}${r.bridge?` <b>Bridge:</b> ${esc(r.bridge)}.`:''}</div><div class="result-actions"><button data-act="save">Save Skill-Link</button><button data-act="copy">Copy answer</button><button data-act="suggest">Suggest improvement</button></div></article>`;$('#result').scrollIntoView({behavior:'smooth',block:'start'})}
function renderNoLink(source,target){current=null;$('#result').innerHTML=`<article class="result-card no-link"><div class="result-head"><small>HONEST RESULT</small><h2>NO SUFFICIENTLY USEFUL SKILL-LINK FOUND</h2><p>JGS could resolve both skills, but the current materialised graph did not produce a specific enough route at the launch threshold.</p></div><div class="answer-grid"><div class="answer"><b>WHAT TO DO</b><p>Try a more specific source or target, or use the ChatGPT prompt below to search your wider background.</p></div><div class="answer"><b>WHY JGS STOPS HERE</b><p>Broad traits such as focus, discipline or teamwork are not treated as a meaningful shortcut by themselves.</p></div></div></article>`}
function renderMessage(msg){$('#result').innerHTML=`<div class="message-card">${esc(msg)}</div>`}
async function run(){const a=$('#source').value.trim(),b=$('#target').value.trim();if(!a||!b)return;$('#find').disabled=true;$('#find').textContent='Finding…';try{await ensureEngine();const source=resolve(a),target=resolve(b);if(!source){renderMessage(`I could not resolve “${a}”. Try a more specific source or choose a skill from Explore Skills.`);return}if(!target){renderMessage(`I could not resolve “${b}”. Try a more specific target or choose a skill from Explore Skills.`);return}if(source.id===target.id){renderMessage('Those resolve to the same skill. Choose a different target.');return}const p=findPath(source,target);p?renderResult(source,target,p):renderNoLink(source,target)}catch(e){renderMessage(e.message||'The Skill-Link engine could not load.')}finally{$('#find').disabled=false;$('#find').textContent='Find My Skill-Link'}}
$('#find').onclick=run;$$('[data-pair]').forEach(b=>b.onclick=()=>{const[a,c]=b.dataset.pair.split('|');$('#source').value=a;$('#target').value=c;run()});['source','target'].forEach(id=>$('#'+id).addEventListener('focus',()=>ensureEngine().catch(()=>{}),{once:true}));
$('#result').onclick=e=>{const a=e.target.dataset.act;if(!a||!current)return;if(a==='save'){const list=JSON.parse(localStorage.getItem(STORE)||'[]');const item={source:current.source,target:current.target,unit:current.r.unit,at:Date.now()};if(!list.some(x=>x.source===item.source&&x.target===item.target))list.unshift(item);localStorage.setItem(STORE,JSON.stringify(list.slice(0,50)));e.target.textContent='Saved ✓'}if(a==='copy')navigator.clipboard?.writeText(resultText(current));if(a==='suggest')openSuggest(current.source,current.target)};
function resultText(c){const r=c.r;return`${c.source} → ${c.target}\n\nTHE EXACT SKILL-LINK\n${r.unit}\n\nWHY THIS WAS CHOSEN\n${r.why}\n\nHOW IT HELPS\n${r.help}\n\nHOW TO TRANSFER IT\n${r.transfer}\n\nWHAT IS STILL NEW\n${r.new}\n\nTRY THIS NOW\n${r.test}`}
function promptText(){const a=$('#source').value||'[EXISTING SKILL / EXPERIENCE]',b=$('#target').value||'[TARGET SKILL]';return`You are my Just Get Skills personal Skill-Link and learning coach.\n\nI already know/do: ${a}\nI want to learn: ${b}\n${current?`JGS found this current exact Skill-Link: ${current.r.unit}. Why: ${current.r.why}.`:'JGS has not yet produced a specific Skill-Link.'}\n\nAnalyse my whole background, including any files I upload. Find 3–7 useful Skill-Links if justified. Search DOWNWARD for the smallest concrete reusable subskill rather than broad similarities. For each use this order: THE EXACT SKILL-LINK; WHY THIS WAS CHOSEN; HOW IT HELPS; HOW TO TRANSFER IT; USE IT HERE; WHAT IS STILL NEW; TRY THIS NOW. Reject weak generic links. Then identify my best head start, best learning route, next session, 7-day plan, progress measures and next decision. Distinguish mechanism-based inference from direct pair evidence and never treat participation as mastery.`}
$('#copyPrompt').onclick=async()=>{await navigator.clipboard?.writeText(promptText());$('#copyPrompt').textContent='Copied ✓';setTimeout(()=>$('#copyPrompt').textContent='Copy personalised AI prompt',1400)};
function worldFor(s){const d=(s.domains||[]).join(' ').toLowerCase(),n=norm(s.name);if(/sport|physical|movement|fitness|football|basketball|rugby|ski|swim|dance|martial/.test(d+' '+n))return'Sport & Movement';if(/music|perform|acting|sing|drum|guitar|piano|magic/.test(d+' '+n))return'Art, Music & Creativity';if(/software|program|data|digital|computer|cyber|web|technology|ai /.test(d+' '+n))return'Technology & Digital';if(/business|finance|sales|market|management|entrepreneur|account|organisation/.test(d+' '+n))return'Business, Money & Organisation';if(/design|craft|making|manufact|carpentry|weld|knit|sew|cook|architecture/.test(d+' '+n))return'Craft, Making & Engineering';if(/science|math|physics|chem|research|reason|analysis/.test(d+' '+n))return'Science & Reasoning';if(/communication|language|teach|social|people|lead|coach|writing|speaking/.test(d+' '+n))return'Communication, Learning & People';if(/outdoor|navigation|driving|gardening|life|home/.test(d+' '+n))return'Life, Outdoor & Navigation';if(/game|chess|poker|strategy|play/.test(d+' '+n))return'Games, Strategy & Play';return'Work & Professions'}
const worldOrder=['Art, Music & Creativity','Science & Reasoning','Technology & Digital','Business, Money & Organisation','Sport & Movement','Craft, Making & Engineering','Communication, Learning & People','Life, Outdoor & Navigation','Games, Strategy & Play','Work & Professions'];
async function renderBrowser(q=''){await ensureEngine();q=norm(q);const root=$('#skillBrowser');let filtered=allSkills.filter(s=>!q||norm(s.name).includes(q)||(s.aliases||[]).some(a=>norm(a).includes(q)));if(q){const show=filtered.slice(0,300);root.innerHTML=`<div class="explore-count"><b>${filtered.length.toLocaleString()}</b> matching skills${filtered.length>300?' · showing first 300':''}</div><div class="chips skill-results">${show.map(s=>`<button data-skill-id="${s.id}">${esc(s.name)}</button>`).join('')}</div>`;return}const groups=new Map(worldOrder.map(w=>[w,[]]));for(const s of allSkills)groups.get(worldFor(s)).push(s);root.innerHTML=`<div class="universe-count"><b>${allSkills.length.toLocaleString()}</b> canonical skills available</div><div class="world-grid">${worldOrder.map(w=>{const ss=groups.get(w);return`<section class="world"><h3>${esc(w)}</h3><p>${ss.length.toLocaleString()} skills in this world</p><div class="chips">${ss.slice(0,24).map(s=>`<button data-skill-id="${s.id}">${esc(s.name)}</button>`).join('')}</div>${ss.length>24?`<button class="world-more" data-world="${esc(w)}">Browse all ${ss.length.toLocaleString()} →</button>`:''}</section>`}).join('')}</div>`}
$('#skillSearch').oninput=e=>renderBrowser(e.target.value).catch(err=>renderMessage(err.message));$('#skillBrowser').onclick=e=>{const id=e.target.dataset.skillId,w=e.target.dataset.world;if(w){ensureEngine().then(()=>{const ss=allSkills.filter(s=>worldFor(s)===w);$('#skillBrowser').innerHTML=`<button class="world-back">← Back to worlds</button><div class="explore-count"><b>${ss.length.toLocaleString()}</b> skills · ${esc(w)}</div><div class="chips skill-results">${ss.map(s=>`<button data-skill-id="${s.id}">${esc(s.name)}</button>`).join('')}</div>`;$('.world-back').onclick=()=>renderBrowser('')});return}if(!id)return;openSkill(skillById.get(id))};
function openSkill(s){if(!s)return;const mapped=(outMap.get(s.id)||[]).slice(0,8).map(c=>skillById.get(c[2])).filter(Boolean);$('#skillDialogBody').innerHTML=`<div class="eyebrow">Skill</div><h2>${esc(s.name)}</h2><p>${esc(s.description||'A canonical skill in the JGS universe.')}</p><div class="dna-card compact"><b>Skill DNA preview</b><div class="chips static">${[...s.subskills.slice(0,6),...s.mechanisms.slice(0,4).map(mechanismName)].filter(Boolean).slice(0,10).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>${mapped.length?`<div class="dna-card compact"><b>Mapped outward Skill-Links</b><div class="chips">${mapped.map(t=>`<button data-dialog-target="${t.id}">${esc(t.name)}</button>`).join('')}</div></div>`:''}<div class="result-actions"><button data-use="source">I already know this</button><button data-use="target">I want to learn this</button><button data-use="dna">Open Skill DNA</button></div>`;$('#skillDialogBody').dataset.skill=s.id;$('#skillDialog').showModal()}
$('#skillDialogBody').onclick=e=>{const targetId=e.target.dataset.dialogTarget;if(targetId){const s=skillById.get($('#skillDialogBody').dataset.skill),t=skillById.get(targetId);$('#skillDialog').close();$('#source').value=s.name;$('#target').value=t.name;show('home');run();return}const use=e.target.dataset.use,id=e.currentTarget.dataset.skill,s=skillById.get(id);if(!use||!s)return;if(use==='source'){$('#source').value=s.name;show('home')}if(use==='target'){$('#target').value=s.name;show('home')}if(use==='dna'){$('#dnaInput').value=s.name;renderDNA(s);show('dna')}$('#skillDialog').close()};
async function renderDNA(input){await ensureEngine();const s=typeof input==='string'?resolve(input):input;if(!s){$('#dnaResult').innerHTML='<div class="message-card">Skill not found.</div>';return}const ids=entitySkillIds(s),base=skillById.get(ids[0])||s,sub=(base.subskills||[]).slice(0,14),mech=(base.mechanisms||[]).slice().sort((a,b)=>mechanismSpec(b)-mechanismSpec(a)).slice(0,10).map(mechanismName),abs=(base.abilities||[]).slice(0,10).map(abilityName);$('#dnaResult').innerHTML=`<div class="dna-card"><h3>${esc(s.name)}</h3><p>${esc(s.description||base.description||'')}</p>${sub.length?`<h4>Subskills</h4><div class="chips static">${sub.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<h4>Processes</h4><div class="chips static">${mech.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h4>Abilities</h4><div class="chips static">${abs.map(x=>`<span>${esc(x)}</span>`).join('')}</div><p class="muted">Skill DNA decomposes the skill. It does not imply that every component transfers to every target.</p></div>`}
$('#dnaBtn').onclick=()=>renderDNA($('#dnaInput').value.trim());
function renderSaved(){const list=JSON.parse(localStorage.getItem(STORE)||'[]');$('#savedList').innerHTML=list.length?list.map((x,i)=>`<div class="saved-item"><div><b>${esc(x.source)} → ${esc(x.target)}</b><div>${esc(x.unit)}</div></div><button data-saved="${i}">Open</button></div>`).join(''):'<p>No saved Skill-Links yet.</p>'}$('#savedList').onclick=e=>{if(e.target.dataset.saved==null)return;const x=JSON.parse(localStorage.getItem(STORE)||'[]')[+e.target.dataset.saved];$('#source').value=x.source;$('#target').value=x.target;show('home');run()};$('#clearSaved').onclick=()=>{localStorage.removeItem(STORE);renderSaved()};
function openSuggest(a='',b=''){$('#suggestFrom').value=a;$('#suggestTo').value=b;$('#suggestDialog').showModal()}$$('[data-open-suggest]').forEach(b=>b.onclick=()=>openSuggest($('#source').value,$('#target').value));$('#sendSuggest').onclick=()=>{const a=$('#suggestFrom').value,b=$('#suggestTo').value,w=$('#suggestWhy').value;location.href=`mailto:corneliusaureliush@gmail.com?subject=${encodeURIComponent(`Just Get Skills Skill-Link suggestion: ${a} → ${b}`)}&body=${encodeURIComponent(`From: ${a}\nTo: ${b}\n\nWhy I think this Skill-Link exists:\n${w}\n\nSubmitted from Just Get Skills.`)}`};$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
async function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('#mainNav button[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='saved')renderSaved();if(v==='explore')renderBrowser($('#skillSearch').value).catch(e=>renderMessage(e.message));if(v==='dna')ensureEngine().catch(()=>{});$('#mainNav').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false');scrollTo({top:0,behavior:'smooth'})}$$('#mainNav button[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#menuToggle').onclick=()=>{const n=$('#mainNav'),o=n.classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(o))};