const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const worlds={"Sport & Movement":["Football","Basketball","Rugby","Skiing","Swimming","Running","Cycling","CrossFit","Martial arts","Dance","Tennis","Boxing","Climbing","Rowing","Surfing"],"Music & Performance":["Drumming","Piano","Singing","Guitar","Music production","Acting","Magic","Public speaking","Improvisation"],"Technology & Digital":["Programming","Python","JavaScript","Web development","Data analysis","Excel","SQL","Cybersecurity","AI & machine learning","Debugging","3D modelling","Graphic design","Video editing"],"Business & People":["Sales","Marketing","Negotiation","Management","Entrepreneurship","Project management","Leadership","Teaching","Coaching","Recruitment"],"Art & Making":["Painting","Photography","Drawing","Carpentry","Sewing","Knitting","Cooking","Gardening","Welding","Architecture"],"Thinking & Games":["Chess","Poker","Gaming","Strategy games","Pattern recognition","Critical thinking","Probability","Mathematics","Physics","Research","Decision making"],"Life & Communication":["Parenting","Driving","Writing","Language learning","Storytelling","Listening","Organisation","Personal finance","Time management","Social skills"]};
const skills=[...new Set(Object.values(worlds).flat())].sort();
const links={
"skiing|football":{unit:"SINGLE-LEG DYNAMIC BALANCE",def:"Control your centre of mass over one support leg while the other leg moves and direction changes.",why:"Skiing repeatedly loads one leg and manages centre of mass while turning. Football repeatedly needs the same control problem when kicking, passing, dribbling, cutting, shielding and recovering after contact.",help:"You may have a head start staying stable while one leg supports your body and the free leg acts.",transfer:"LOAD ONE LEG → CONTROL CENTRE OF MASS → MOVE THE FREE LEG → RECENTRE → CHANGE DIRECTION",use:"Kicking · passing · dribbling · cutting · shielding · contact recovery",new:"Ball control, passing, shooting, scanning, tactical positioning and football-specific decisions still require direct practice.",test:"Try 3 sets of slow single-leg ball touches and cuts. Compare control when you deliberately use the same centred, loaded-leg feeling you use when skiing."},
"magic|football":{unit:"INTENTION CONCEALMENT + FALSE-CUE GENERATION",def:"Make another person predict the wrong action by controlling visible cues while protecting your real intention.",why:"Magic manipulates an observer's expectations. Football feints, disguised passes and body swerves rely on the same prediction-control problem.",help:"You may understand deception earlier than a beginner who only thinks about the physical move.",transfer:"SHOW A BELIEVABLE CUE → LET THE DEFENDER COMMIT → EXECUTE THE REAL ACTION",use:"Body feints · fake shots · disguised passes · changes of direction",new:"Football timing, ball control, pace, defender distance and tactical context remain specific to football.",test:"Practise one feint slowly. Judge success by whether the defender reacts to the false cue."},
"knitting|programming":{unit:"STATE TRACKING + ERROR TRACING",def:"Maintain where you are in a structured sequence and trace a mismatch back to the point where state changed incorrectly.",why:"Knitting requires tracking stitch state, pattern position and mistakes across a sequence. Programming requires tracking program state, execution order and the source of errors.",help:"You may already be comfortable with structured sequences, local errors and correcting a process without restarting everything.",transfer:"TRACK STATE → NOTICE MISMATCH → TRACE BACK → CORRECT THE LOCAL STEP → CONTINUE",use:"Debugging · loops · sequence logic · stateful programs",new:"Syntax, data structures, algorithms and software architecture remain programming-specific.",test:"When debugging a tiny program, write down the expected state after each step as you would count pattern progress in knitting."},
"drumming|language learning":{unit:"RHYTHMIC TIMING + SOUND-SEQUENCE CHUNKING",def:"Track repeating sound patterns, timing accents and sequence structure as one organised unit.",why:"Drumming trains timing, subdivision and recurring sound sequences. Spoken language also contains stress, rhythm, timing and repeatable sound chunks.",help:"You may pick up speech rhythm and pronunciation patterns faster than someone treating every syllable separately.",transfer:"HEAR THE PHRASE AS RHYTHM → MARK STRESS → COPY THE TIMING → ADD WORDS",use:"Pronunciation · sentence stress · listening · shadowing",new:"Vocabulary, grammar, meaning and language-specific sounds still require direct learning.",test:"Shadow one short sentence as if it were a drum phrase before focusing on exact words."},
"chess|football":{unit:"ANTICIPATION FROM POSITIONAL CUES",def:"Use the current arrangement of players or pieces to predict likely next actions before they happen.",why:"Chess trains prediction from position, threats and constrained options. Football also rewards reading shape, body orientation, space and likely next actions before the move unfolds.",help:"You may learn to scan for informative cues and prepare earlier instead of reacting only after the action begins.",transfer:"SCAN THE POSITION → IDENTIFY CONSTRAINTS → PREDICT LIKELY ACTION → PREPARE RESPONSE",use:"Defensive positioning · pressing · passing lanes · off-ball movement",new:"Football perception is faster, embodied and continuous; technique and tactical knowledge remain sport-specific.",test:"Pause a football clip before a pass and predict the next two likely options from player positions alone."}};
const dna={Football:["single-leg dynamic balance","scanning","first touch","trajectory prediction","change of direction","opponent anticipation","space creation","passing weight"],Skiing:["single-leg dynamic balance","centre-of-mass control","edge control","terrain reading","weight transfer","rapid corrective movement"],Magic:["intention concealment","false-cue generation","audience modelling","timing","attention guidance"],Drumming:["limb independence","rhythmic timing","sequence chunking","auditory-motor coupling","tempo control"],Programming:["state tracking","error tracing","decomposition","sequence logic","debugging","abstraction"],Knitting:["state tracking","error tracing","pattern counting","fine motor sequencing","procedural consistency"],Chess:["positional cue reading","opponent modelling","prediction","trade-off evaluation","state tracking"]};
let current=null;
function norm(x){return String(x||'').trim().toLowerCase()}function esc(x){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]))}
function infer(a,b){const k=`${norm(a)}|${norm(b)}`;if(links[k])return links[k];return{unit:"NO STRONG SPECIFIC SKILL-LINK YET",def:"The launch engine does not currently have a sufficiently specific reusable unit for this exact pair.",why:"JGS avoids forcing a clever analogy when it cannot name a concrete shared behaviour.",help:"A trustworthy no is more useful than pretending broad traits such as focus or discipline create a learning advantage.",transfer:"Use the ChatGPT prompt below to analyse your wider experience and search for a stronger route.",use:`Look for a concrete repeated task in ${b}.`,new:`${b} still needs to be learned directly unless a stronger transferable foundation is identified.`,test:"Describe one concrete task you repeatedly perform in the source and one concrete task required in the target. Compare the movement, decision or information process."}}
function render(a,b,r){current={a,b,...r};$('#result').innerHTML=`<article class="result-card"><div class="result-head"><small>THE EXACT SKILL-LINK</small><h2>${esc(r.unit)}</h2><p>${esc(r.def)}</p></div><div class="answer-grid"><div class="answer"><b>WHY THIS WAS CHOSEN</b><p>${esc(r.why)}</p></div><div class="answer"><b>HOW IT HELPS</b><p>${esc(r.help)}</p></div><div class="answer"><b>HOW TO TRANSFER IT</b><p class="transfer-rule">${esc(r.transfer)}</p></div><div class="answer"><b>USE IT HERE</b><p>${esc(r.use)}</p></div><div class="answer"><b>WHAT IS STILL NEW</b><p>${esc(r.new)}</p></div><div class="answer"><b>TRY THIS NOW</b><p>${esc(r.test)}</p></div></div><div class="result-actions"><button data-act="save">Save Skill-Link</button><button data-act="copy">Copy answer</button><button data-act="suggest">Suggest improvement</button></div></article>`;$('#result').scrollIntoView({behavior:'smooth',block:'start'})}
function run(a=$('#source').value,b=$('#target').value){if(!a.trim()||!b.trim())return;render(a,b,infer(a,b))}
$('#find').onclick=()=>run();$$('[data-pair]').forEach(b=>b.onclick=()=>{const[a,c]=b.dataset.pair.split('|');$('#source').value=a;$('#target').value=c;run(a,c)});
$('#result').onclick=e=>{const a=e.target.dataset.act;if(!a||!current)return;if(a==='save'){const list=JSON.parse(localStorage.getItem('jgsSkillLinks')||'[]');list.unshift({...current,at:Date.now()});localStorage.setItem('jgsSkillLinks',JSON.stringify(list.slice(0,50)));e.target.textContent='Saved ✓'}if(a==='copy')navigator.clipboard?.writeText(resultText(current));if(a==='suggest')openSuggest(current.a,current.b)};
function resultText(r){return`${r.a} → ${r.b}\n\nTHE EXACT SKILL-LINK\n${r.unit}\n\nWHY THIS WAS CHOSEN\n${r.why}\n\nHOW IT HELPS\n${r.help}\n\nHOW TO TRANSFER IT\n${r.transfer}\n\nWHAT IS STILL NEW\n${r.new}\n\nTRY THIS NOW\n${r.test}`}
function promptText(){const a=$('#source').value||'[EXISTING SKILL / EXPERIENCE]',b=$('#target').value||'[TARGET SKILL]';return`You are my Just Get Skills personal Skill-Link and learning coach.\n\nI already know/do: ${a}\nI want to learn: ${b}\n${current?`JGS found this current exact Skill-Link: ${current.unit}. Why: ${current.why}.`:'JGS has not yet produced a specific Skill-Link.'}\n\nAnalyse my whole background, including any files I upload. Find 3–7 useful Skill-Links if justified. Search DOWNWARD for the smallest concrete reusable subskill rather than broad similarities. For each use this order: THE EXACT SKILL-LINK; WHY THIS WAS CHOSEN; HOW IT HELPS; HOW TO TRANSFER IT; USE IT HERE; WHAT IS STILL NEW; TRY THIS NOW. Reject weak generic links. Then identify my best head start, best learning route, next session, 7-day plan, progress measures and next decision. Distinguish mechanism-based inference from direct pair evidence and never treat participation as mastery.`}
$('#copyPrompt').onclick=async()=>{await navigator.clipboard?.writeText(promptText());$('#copyPrompt').textContent='Copied ✓';setTimeout(()=>$('#copyPrompt').textContent='Copy personalised AI prompt',1400)};
skills.forEach(x=>{const o=document.createElement('option');o.value=x;$('#skillList').append(o)});
function renderBrowser(q=''){q=norm(q);$('#skillBrowser').innerHTML=`<div class="world-grid">${Object.entries(worlds).map(([w,ss])=>{const f=ss.filter(s=>!q||norm(s).includes(q)||norm(w).includes(q));return f.length?`<section class="world"><h3>${esc(w)}</h3><p>${f.length} visible skills</p><div class="chips">${f.map(s=>`<button data-skill="${esc(s)}">${esc(s)}</button>`).join('')}</div></section>`:''}).join('')}</div>`}
renderBrowser();$('#skillSearch').oninput=e=>renderBrowser(e.target.value);$('#skillBrowser').onclick=e=>{const s=e.target.dataset.skill;if(!s)return;$('#skillDialogBody').innerHTML=`<div class="eyebrow">Skill</div><h2>${esc(s)}</h2><p>Choose how to use this skill.</p><div class="result-actions"><button data-use="source">I already know this</button><button data-use="target">I want to learn this</button><button data-use="dna">Open Skill DNA</button></div>`;$('#skillDialogBody').dataset.skill=s;$('#skillDialog').showModal()};
$('#skillDialogBody').onclick=e=>{const use=e.target.dataset.use,s=e.currentTarget.dataset.skill;if(!use)return;if(use==='source'){$('#source').value=s;show('home')}if(use==='target'){$('#target').value=s;show('home')}if(use==='dna'){$('#dnaInput').value=s;renderDNA(s);show('dna')}$('#skillDialog').close()};
function renderDNA(s){const parts=dna[s]||["task decomposition","state tracking","feedback-dependent refinement","error detection","timing or sequencing","target-specific technique"];$('#dnaResult').innerHTML=`<div class="dna-card"><h3>${esc(s)}</h3><p>Useful candidate subskills to inspect:</p><ul>${parts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="muted">Skill DNA is a decomposition aid, not proof that every listed component transfers to every target.</p></div>`}
$('#dnaBtn').onclick=()=>{const s=$('#dnaInput').value.trim();if(s)renderDNA(s)};
function renderSaved(){const list=JSON.parse(localStorage.getItem('jgsSkillLinks')||'[]');$('#savedList').innerHTML=list.length?list.map((x,i)=>`<div class="saved-item"><div><b>${esc(x.a)} → ${esc(x.b)}</b><div>${esc(x.unit)}</div></div><button data-saved="${i}">Open</button></div>`).join(''):'<p>No saved Skill-Links yet.</p>'}$('#savedList').onclick=e=>{if(e.target.dataset.saved==null)return;const x=JSON.parse(localStorage.getItem('jgsSkillLinks')||'[]')[+e.target.dataset.saved];$('#source').value=x.a;$('#target').value=x.b;render(x.a,x.b,x);show('home')};$('#clearSaved').onclick=()=>{localStorage.removeItem('jgsSkillLinks');renderSaved()};
function openSuggest(a='',b=''){$('#suggestFrom').value=a;$('#suggestTo').value=b;$('#suggestDialog').showModal()}$$('[data-open-suggest]').forEach(b=>b.onclick=()=>openSuggest($('#source').value,$('#target').value));$('#sendSuggest').onclick=()=>{const a=$('#suggestFrom').value,b=$('#suggestTo').value,w=$('#suggestWhy').value;location.href=`mailto:corneliusaureliush@gmail.com?subject=${encodeURIComponent(`Just Get Skills Skill-Link suggestion: ${a} → ${b}`)}&body=${encodeURIComponent(`From: ${a}\nTo: ${b}\n\nWhy I think this Skill-Link exists:\n${w}\n\nSubmitted from Just Get Skills.`)}`};$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('#mainNav button[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='saved')renderSaved();$('#mainNav').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false');scrollTo({top:0,behavior:'smooth'})}$$('#mainNav button[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#menuToggle').onclick=()=>{const n=$('#mainNav'),o=n.classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(o))};